package org.mhsun.pc.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MbgCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public MbgCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPcCommentIsNull() {
            addCriterion("pc_comment is null");
            return (Criteria) this;
        }

        public Criteria andPcCommentIsNotNull() {
            addCriterion("pc_comment is not null");
            return (Criteria) this;
        }

        public Criteria andPcCommentEqualTo(String value) {
            addCriterion("pc_comment =", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentNotEqualTo(String value) {
            addCriterion("pc_comment <>", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentGreaterThan(String value) {
            addCriterion("pc_comment >", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentGreaterThanOrEqualTo(String value) {
            addCriterion("pc_comment >=", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentLessThan(String value) {
            addCriterion("pc_comment <", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentLessThanOrEqualTo(String value) {
            addCriterion("pc_comment <=", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentLike(String value) {
            addCriterion("pc_comment like", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentNotLike(String value) {
            addCriterion("pc_comment not like", value, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentIn(List<String> values) {
            addCriterion("pc_comment in", values, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentNotIn(List<String> values) {
            addCriterion("pc_comment not in", values, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentBetween(String value1, String value2) {
            addCriterion("pc_comment between", value1, value2, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcCommentNotBetween(String value1, String value2) {
            addCriterion("pc_comment not between", value1, value2, "pcComment");
            return (Criteria) this;
        }

        public Criteria andPcStarIsNull() {
            addCriterion("pc_star is null");
            return (Criteria) this;
        }

        public Criteria andPcStarIsNotNull() {
            addCriterion("pc_star is not null");
            return (Criteria) this;
        }

        public Criteria andPcStarEqualTo(Byte value) {
            addCriterion("pc_star =", value, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarNotEqualTo(Byte value) {
            addCriterion("pc_star <>", value, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarGreaterThan(Byte value) {
            addCriterion("pc_star >", value, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarGreaterThanOrEqualTo(Byte value) {
            addCriterion("pc_star >=", value, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarLessThan(Byte value) {
            addCriterion("pc_star <", value, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarLessThanOrEqualTo(Byte value) {
            addCriterion("pc_star <=", value, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarIn(List<Byte> values) {
            addCriterion("pc_star in", values, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarNotIn(List<Byte> values) {
            addCriterion("pc_star not in", values, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarBetween(Byte value1, Byte value2) {
            addCriterion("pc_star between", value1, value2, "pcStar");
            return (Criteria) this;
        }

        public Criteria andPcStarNotBetween(Byte value1, Byte value2) {
            addCriterion("pc_star not between", value1, value2, "pcStar");
            return (Criteria) this;
        }

        public Criteria andFkIsNull() {
            addCriterion("fk is null");
            return (Criteria) this;
        }

        public Criteria andFkIsNotNull() {
            addCriterion("fk is not null");
            return (Criteria) this;
        }

        public Criteria andFkEqualTo(Integer value) {
            addCriterion("fk =", value, "fk");
            return (Criteria) this;
        }

        public Criteria andFkNotEqualTo(Integer value) {
            addCriterion("fk <>", value, "fk");
            return (Criteria) this;
        }

        public Criteria andFkGreaterThan(Integer value) {
            addCriterion("fk >", value, "fk");
            return (Criteria) this;
        }

        public Criteria andFkGreaterThanOrEqualTo(Integer value) {
            addCriterion("fk >=", value, "fk");
            return (Criteria) this;
        }

        public Criteria andFkLessThan(Integer value) {
            addCriterion("fk <", value, "fk");
            return (Criteria) this;
        }

        public Criteria andFkLessThanOrEqualTo(Integer value) {
            addCriterion("fk <=", value, "fk");
            return (Criteria) this;
        }

        public Criteria andFkIn(List<Integer> values) {
            addCriterion("fk in", values, "fk");
            return (Criteria) this;
        }

        public Criteria andFkNotIn(List<Integer> values) {
            addCriterion("fk not in", values, "fk");
            return (Criteria) this;
        }

        public Criteria andFkBetween(Integer value1, Integer value2) {
            addCriterion("fk between", value1, value2, "fk");
            return (Criteria) this;
        }

        public Criteria andFkNotBetween(Integer value1, Integer value2) {
            addCriterion("fk not between", value1, value2, "fk");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampIsNull() {
            addCriterion("commnt_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampIsNotNull() {
            addCriterion("commnt_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampEqualTo(Date value) {
            addCriterion("commnt_timestamp =", value, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampNotEqualTo(Date value) {
            addCriterion("commnt_timestamp <>", value, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampGreaterThan(Date value) {
            addCriterion("commnt_timestamp >", value, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("commnt_timestamp >=", value, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampLessThan(Date value) {
            addCriterion("commnt_timestamp <", value, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampLessThanOrEqualTo(Date value) {
            addCriterion("commnt_timestamp <=", value, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampIn(List<Date> values) {
            addCriterion("commnt_timestamp in", values, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampNotIn(List<Date> values) {
            addCriterion("commnt_timestamp not in", values, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampBetween(Date value1, Date value2) {
            addCriterion("commnt_timestamp between", value1, value2, "commntTimestamp");
            return (Criteria) this;
        }

        public Criteria andCommntTimestampNotBetween(Date value1, Date value2) {
            addCriterion("commnt_timestamp not between", value1, value2, "commntTimestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pc_comment
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 20 01:05:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pc_comment
     *
     * @mbg.generated Mon Aug 20 01:05:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}